- name: Chia Test Environment
  hosts: fullnode
  remote_user: ansible
  become: yes
  tasks:
    - apt:
        update_cache: yes
        name: [
          openssh-server, ubuntu-desktop-minimal, xrdp, git
          ]
        state: latest
    - apt:
        state: present
        deb: "{{chia_package}}"
    - apt:
        upgrade: yes