# Tasks specific for Wallet (all Nodes)
- name: Chia Test Environment Wallet
  hosts: wallet
  remote_user: ansible
  become: yes
  tasks:
    - name: Install necessary packages (lasts long 30 min to 2 hours)
      apt:
        update_cache: yes
        name: [
          openssh-server, vim, micro, ubuntu-desktop-minimal, xrdp, git, curl,
          htop, gnome-tweaks, wget, apt-transport-https, software-properties-common,
          asciinema, kazam
          ]
        state: latest
    - name: Install latest Chia package
      apt:
        state: present
        deb: "{{chia_package}}"
    - apt:
        upgrade: yes
    - name: Fix xrdp colord issue
      ansible.builtin.copy:
        src: files/policykit/02-allow-colord.conf
        dest: /etc/polkit-1/localauthority.conf.d/02-allow-colord.conf
        mode: '644'
    - name: dedicated user for chia
      ansible.builtin.user:
        name: chia
        comment: chia dedicated user
        shell: /bin/bash
        password: "{{ 'chiatest' | password_hash('sha512', 'mysecretsalt') }}"

#    - name: Your PublicKey
#      debug: msg="{{item}}"
#      loop: "{{ lookup('file', '~/.ssh/id_rsa.pub').splitlines() }}"

    - name: Chia User ssh folder
      ansible.builtin.file:
        state: directory
        path: /home/chia/.ssh
        owner: chia
        group: chia
    - name: Chia User authorized_keys fille
      ansible.builtin.file:
        state: touch
        path: /home/chia/.ssh/authorized_keys
        mode: '0600'
        owner: chia
        group: chia
    - name: Install SSH Key
      loop: "{{ lookup('file', '~/.ssh/id_rsa.pub').splitlines() }}"
      ansible.builtin.lineinfile:
        path: /home/chia/.ssh/authorized_keys
        line: "{{item}}"
        state: present

    - name: configure chia for test environment
      become_user: chia
      block:
      - name: configure chia testnet
        ansible.builtin.shell: 
          cmd: |
            chia init
            chia configure --testnet true
          creates: /home/chia/.chia/mainnet/config/config.yaml
      - name: download and unpack chia testnet database
        when: download_current_testnet_database == true
        ansible.builtin.shell:
          cmd: |
            cd /home/chia/.chia/mainnet/db
            wget https://databases.chia.net/file/chia-public-databases/blockchain_v2_testnet10.sqlite.gz
            gunzip blockchain_v2_testnet10.sqlite.gz
          creates: /home/chia/.chia/mainnet/db/blockchain_v2_testnet10.sqlite
      - name: create first private key and start farm
        ansible.builtin.shell:
          cmd: |
            chia keys generate
            echo "first_key_generated" > ~/.chia/first_key_generated.txt
          creates: ~/.chia/first_key_generated.txt

      #Powershell on x64 Systems
    - name: Install Powershell (x86_64)
      when: ansible_facts['architecture'] == 'x86_64'
      block:
        - name: Install Microsoft Repository
          ansible.builtin.shell:
            cmd: |
              wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
              dpkg -i packages-microsoft-prod.deb
            creates: /etc/apt/trusted.gpg.d/microsoft.gpg
        - name: Install Powershell (x86_64)
          apt:
            update_cache: yes
            clean: yes
            name: [
              powershell
              ]
            state: latest
      

      #Powershell on aarch64 Systems
    - name: Install Powershell (aarch64)
      when: ansible_facts['architecture'] == 'aarch64'
      block:
        - name: Install Powershell for aarch64 via Binary archive
          ansible.builtin.shell:
            cmd: |
              curl -L -o /tmp/powershell.tar.gz {{powershell_package}}
              mkdir -p /opt/microsoft/powershell/7
              tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7
              chmod +x /opt/microsoft/powershell/7/pwsh
              ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh
            creates: /opt/microsoft/powershell/7/pwsh

    - name: Get ChiaShell from Github
      become_user: chia
      ansible.builtin.shell:
        cmd: |
          mkdir -p /home/chia/.config/powershell
          mkdir -p /home/chia/git
          git -C /home/chia/git clone https://github.com/RudolfAchter/ChiaShell.git
        creates: /home/chia/git/ChiaShell/Powershell/Modules/ChiaShell/ChiaShell.psm1
    - name: Make ChiaShell safe directory
      ansible.builtin.copy:
        src: files/git/.gitconfig
        dest: /home/chia/.gitconfig
    - name: Pull Current ChiaShell Version
      ansible.builtin.shell:
        cmd: |
          git config --global --add safe.directory /home/chia/git/ChiaShell
          git -C /home/chia/git/ChiaShell pull
      register: pull_chiashell
    - name: ChiaShell pull result
      debug:
        var: pull_chiashell
    - name: Install Modules
      ansible.builtin.shell:
        executable: pwsh
        cmd: |
          Install-Module PSReadline -Force
          Install-Module Terminal-Icons -Force
          Install-Module Microsoft.PowerShell.ConsoleGuiTools -Force
    - name: Set Powershell Profile for Chia
      become_user: chia
      ansible.builtin.copy:
        src: files/powershell/Microsoft.PowerShell_profile.ps1
        dest: /home/chia/.config/powershell
#Tasks specific for FullNode
- name: Chia Test Environment FullNode
  hosts: fullnode
  remote_user: ansible
  become: yes
  tasks:
    - name: install chia service
      ansible.builtin.copy:
        src: files/systemd/chia.service
        dest: /lib/systemd/system/chia.service
        owner: root
        group: root
        mode: '0644'
    - name: enable chia service
      ansible.builtin.service:
        name: chia
        enabled: yes



#Tasks specific for Farmer
- name: Chia Test Environment Farmer
  hosts: farmer
  tasks:
    - name: Install MadMax plotter
      when: install_madmax == true
      block:
        - name: MadMax plotter prerequisites
          apt:
            update_cache: yes
            name: [libsodium-dev, cmake, g++, git, build-essential]
            state: latest
        - name: Install MadMax plotter from source
          ansible.builtin.shell:
            cmd: |
              cd ~
              git clone https://github.com/madMAx43v3r/chia-plotter.git
              cd chia-plotter
              git submodule update --init
              ./make_devel.sh
              cp ~/chia_plot/build/chia_plot /usr/local/bin
            creates: /usr/local/bin/chia_plot


